version: 2

models:
  - name: customers_model
    description: "Transformed customers model"
    columns:
      - name: customer_id
        description: "Unique identifier generated for the model"
        tests:
          - not_null
          - unique
